services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: babelingo
      POSTGRES_PASSWORD: babelingo
      POSTGRES_DB: babelingo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: